version: '3.3'
services:
    fhir_iomeds:
        ports:
            - '8000:4434'
        volumes:
            - 'TKW_ROOT/FHIR_IOMEDS_OutputDir:/home/service/data' 
            - 'TKW_ROOT/ITKMessageDefinition:/home/service/fhir' 
            - 'TKW_ROOT/certs:/home/service/certs'
        image: 'nhsdigitalmait/fhir_iomeds:20211001-1004-contextpath'
