version: '3.3'
services:
    fhir_iomeds:
        ports:
            - '8000:4434'
        volumes:
            - '/home/prod/IOMedsOutput:/home/service/data' 
            - '/home/prod/iomeds_profiles:/home/service/fhir' 
            - '/home/prod/certs:/home/service/certs'
        image: 'nhsdigitalmait/fhir_iomeds:20210907-1004'
