version: '3.3'
services:
    fhir_iomeds:
        network_mode : "host"
#        ports:
#            - '8000:4434'
        volumes:
            - '/home/riro/Scratch/data:/home/service/data'
            - '/home/riro/Technical_Specialist_Folder/TerminologyServer/TerminologyServerLoginDetails:/home/service/access_token'
            - '/home/riro/Technical_Specialist_Folder/fhir/Assets/IOMEDS_ITKMessageDefinition:/home/service/fhir' 
            - '/home/riro/TKW-5.0.5/TKW/config/FHIR_IOMEDS/certs:/home/service/certs'
        environment:
            - terminologyserveraccesstokenlocation=/home/service/access_token/fhir_terminology_server_access_token.txt
        image: 'nhsdigitalmait/fhir_iomeds:20220309'
